// antd-designer/src/designer/wrapper/ComponentWrapper.tsx
import React, {ComponentClass} from 'react';
import {CloseCircleOutlined} from '@ant-design/icons';
import className from 'classnames';
import createReactClass from 'create-react-class';
import {ReactComponentProps} from "../types";

const hoistNonReactStatics = require('hoist-non-react-statics');

function ComponentWrapper<T>(WrappedComponent: ComponentClass<ReactComponentProps<T>>) {
    // noinspection JSAnnotator
    const componentLayout = createReactClass({
        displayName: 'ComponentWrapper',
        getInitialState() {
            return {
                renderCounter: 0,
                active: false
            }
        },

        /**
         * shouldComponentUpdate 默认不是对象的深层比较，采用标志位的方式
         * 此方法代替foreUpdate
         */
        forceRender() {
            const {renderCounter} = this.state;
            this.setState({
                renderCounter: (renderCounter || 0) + 1
            });
        },

        onActive(e: Event) {
            if (e) {
                e.stopPropagation();
            }

            // TODO
            /* if (FormStudio.activeComponent) {
                 FormStudio.activeComponent.unActive();
             }

             FormStudio.activeComponent = this;*/

            this.setState({
                active: true
            })
        },
        unActive() {
            this.setState({
                active: false
            })
        },
        getWrappedInstance() {
            return this.wrappedInstance;
        },
        setWrappedInstance(ref: any) {
            this.wrappedInstance = ref;
        },
        render() {
            const {active, renderCounter} = this.state;
            const {definition} = this.props;
            return (
                <>
                    <div className={className({'component': true, 'component-field': true, 'active': active})}
                         onClick={this.onActive}>
                            <span className="fm-btn-remove">
                              <CloseCircleOutlined/>
                            </span>
                        <div>
                            <div className="field-title">
                                <span>{definition.title}</span>
                            </div>
                            <div className="field-content">
                                <WrappedComponent
                                    {...this.props}
                                    definition={definition}
                                    renderCounter={renderCounter}
                                    ref={this.setWrappedInstance}/>
                            </div>
                        </div>
                    </div>
                </>
            );
        }
    });

    componentLayout.displayName = `ComponentWrapper(${WrappedComponent.displayName || WrappedComponent.name || 'WrappedComponent'})`;

    return hoistNonReactStatics(componentLayout, WrappedComponent);
}

export default ComponentWrapper;

// antdv-designer/src/designer/wrapper/ComponentWrapper.vue
<template>
  <div class="component component-field" :class="{active: active}" @click="onActive">
   <span class="fm-btn-remove" v-on:click="onDelete" v-if="active">
    <CloseCircleOutlined/>
    </span>
    <div>
      <div class="field-title">
        <span>{{ title }}</span>
      </div>
      <div class="field-content">
        <slot/>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import {CloseCircleOutlined} from '@ant-design/icons-vue';
import {defineComponent} from "vue";

export default defineComponent({
  name: "ComponentWrapper",
  components: {
    CloseCircleOutlined
  },
  props: {
    active: Boolean,
    title: String
  },
  emits: ['onDelete', 'onActive'],
  setup(props: any, ctx: any) {

    function onDelete(e: Event) {
      e.stopPropagation();
      ctx.emit('onDelete')
    }

    function onActive(e: Event) {
      e.stopPropagation();
      ctx.emit('onActive')
    }

    return {
      onDelete,
      onActive

    }
  }
})

</script>

<style scoped>

</style>
