// antdv-designer/src/designer/FormView.vue
<template>
  <div class="form-view" :style="{width: formDefinition.width || '778px'}">
    <div class="form-head">
      <div class="form-name">{{ formDefinition.title }}</div>
      <div class="form-description">{{ formDefinition.description }}</div>
    </div>
    <div class="form-content">
      <LayoutWrapper :toolbarAble="false">
        <Component :is="getComponent(definition.type)" :definition="definition"/>
      </LayoutWrapper>
    </div>
  </div>
</template>

<script lang="ts">
import {defineComponent} from "vue";
import {FormHelper} from "@/designer/helper";
import LayoutWrapper from "@/designer/wrapper/LayoutWrapper.vue";
import {ComponentDefinition, FormDefinition} from "@@/types";

function FormDefinition() {
  return {} as FormDefinition
}

function Definition() {
  return {} as ComponentDefinition<any>;
}

export default defineComponent({
  name: "FormView",
  components: {LayoutWrapper},
  props: {
    formDefinition: FormDefinition,
    definition: Definition
  },
  setup() {
    function getComponent(type: string) {
      return FormHelper.getComponent(type)
    }

    return {
      getComponent,
    }
  }
})
</script>

<style scoped>

</style>

// antd-designer/src/designer/FormView.tsx
import React, {PureComponent, ReactElement} from 'react'
import {FormDefinition} from "../../../src/types";
import FormStudio from "../../../src/FormStudio";
import {FactoryRenders} from "./helper";

require('./formView.less');

export default class FormView extends PureComponent<{ formDefinition: FormDefinition }> {

    private LinearLayout: ReactElement | null = null;

    componentWillMount() {
        const componentRender = FactoryRenders.getRender("LinearLayout");
        this.LinearLayout = componentRender.renderComponent(FormStudio.definition!)({
            focusAble: false,
            toolbarAble: false
        });
    }

    render() {
        const {formDefinition} = this.props;

        return (
            <div style={{width: formDefinition.width || '778px'}}>
                <div className="scroll-wrapper">
                    <div className="form-view">
                        <div className="form-head">
                            <p className="form-name"/>
                            <div className="form-description">{formDefinition.description}</div>
                        </div>
                        <div
                            className="form-content"
                        >
                            {this.LinearLayout}
                        </div>
                    </div>
                </div>
            </div>
        );
    }
}
