// antd-designer/src/designer/FormPropsEditor.tsx
import React, {PureComponent} from 'react'
import {FormHelper} from "./helper";
import {ReactComponentGroupState} from "./types";
import {FormDefinition} from "../../../src/types";
import {Form, FormInstance, Input, InputNumber} from "antd";
import {mergeObject} from "../../../src/utils";
import TextArea from "antd/es/input/TextArea";

require('../../../src/style/formView.less');

type FormPropsEditorProps = {
    definition: FormDefinition;
}

/**
 * 属性编辑器
 */
class FormPropsEditor extends PureComponent<FormPropsEditorProps, ReactComponentGroupState<any>> {

    private readonly refForm = React.createRef<FormInstance>();


    onValuesChange(changedValues: any) {
        console.log('onValuesChange', changedValues)
        const {definition} = this.props;
        for (const field of Object.keys(changedValues)) {
            mergeObject(field, changedValues[field], definition);
        }

        FormHelper.formView!.forceRender();
    }

    override render() {
        const {definition} = this.props;
        return (
            <div>
                <Form
                    ref={this.refForm}
                    size="middle"
                    layout="vertical"
                    onValuesChange={(changedValues) => this.onValuesChange(changedValues)}
                >
                    <Form.Item
                        initialValue={definition.title}
                        label="标题"
                        name="title"
                        rules={[
                            {required: true}
                        ]}
                    >
                        <Input/>
                    </Form.Item>
                    <Form.Item
                        initialValue={definition.width}
                        label="宽度"
                        name="width"
                    >
                        <InputNumber/>
                    </Form.Item>
                    <Form.Item
                        initialValue={definition.description}
                        label="描述"
                        name="description"
                    >
                        <TextArea rows={4} placeholder="请输入描述"/>
                    </Form.Item>
                </Form>
            </div>
        );
    }
}

export default FormPropsEditor;

// antdv-designer/src/designer/FormPropsEditor.vue
<template>
  <a-form
    v-if="formModel != null"
    :model="formModel"
    :label-col="labelCol"
    :wrapper-col="wrapperCol"
    ref="refForm"
  >
    <a-form-item label="标题" name="title" :rules="titleRules">
      <a-input
        placeholder="标题"
        v-model:value="formModel.title"
        @change="onFieldChange('title')"
      />
    </a-form-item>

    <a-form-item label="描述" name="description">
      <a-textarea
        placeholder="描述"
        v-model:value="formModel.description"
        @change="onFieldChange('description')"
      />
    </a-form-item>
  </a-form>
</template>

<script lang="ts">
  import { defineComponent, ref } from 'vue';
  import { Form, Input, Textarea } from 'ant-design-vue';
  import { getFieldValue, mergeObj2Obj } from '@@/utils';
  import { FormHelper } from './helper';
  import FormStudio from '@@/FormStudio';
  import { FormDefinition } from '@@/types';

  const titleRules = [
    {
      type: 'string',
      max: 50,
      min: 1,
    },
    {
      required: true,
      message: '字段必填',
    },
  ];

  export default defineComponent({
    name: 'FormPropsEditor',
    components: {
      AForm: Form,
      AFormItem: Form.Item,
      AInput: Input,
      ATextarea: Textarea,
    },
    setup() {
      const refForm = ref<any>(null);
      const formModel = ref<FormDefinition>(JSON.parse(JSON.stringify(FormStudio.formDef)));
      const definition = ref<any>(FormStudio.formDef);

      function onFieldChange(fieldPath: string) {
        if (refForm.value) {
          // Fix: form 不支持 `a.b.c` 的格式
          formModel.value = {
            ...formModel.value,
            [fieldPath]: getFieldValue(formModel.value, fieldPath)
          }
          refForm.value.validate([fieldPath]).then(() => {
            mergeObj2Obj(fieldPath, formModel.value, definition.value);
            FormHelper.formView!.$forceUpdate();
          });
        }
      }

      return {
        onFieldChange,
        refForm,
        formModel,
        titleRules,
        labelCol: { span: 4 },
        wrapperCol: { span: 20 },
      };
    },
  });
</script>

<style scoped lang="less"></style>
