// antd-designer/src/designer/FormDesigner.tsx
import React, {PureComponent, useRef, useEffect} from 'react'
import {Tabs} from 'antd';
import FormView from './FormView';
import componentStyle from '@@/style/component.module.less';
import ComponentPropsEditor from './ComponentPropsEditor';
import FormStudio from "@@/FormStudio";
import {Component, ComponentFactory, FactoryGroup} from "@@/types";
import {draggable} from "@/designer/lib/sortable";
import FormPropsEditor from "./FormPropsEditor";

require('./components');

require('./layout');

function FormComponentList(props: {
    widgetList: ComponentFactory<any>[]
}) {
    const domRef = useRef(null);
    useEffect(() => {
        draggable(domRef.current, props.widgetList);
    }, [])
    return (<>
        <div className={componentStyle.widgetList} ref={domRef}>
            {props.widgetList.map(it => {
                return <div
                    draggable
                    className={componentStyle.widgetItem}
                >
                    {it.title}
                </div>
            })}
        </div>
    </>);
}

class FormDesigner extends PureComponent {

    override render() {
        return (
            <div className="form-designer">
                <div className="form-widget">
                    <Tabs>
                        <Tabs.TabPane tab="表单组件" key='1'>
                            <FormComponentList
                                widgetList={FormStudio.factoryList.filter(it => it.group == FactoryGroup.Component)}/>
                        </Tabs.TabPane>
                        <Tabs.TabPane tab="布局" key='2'>
                            <FormComponentList
                                widgetList={FormStudio.factoryList.filter(it => it.group == FactoryGroup.Layout)}/>
                        </Tabs.TabPane>
                    </Tabs>
                </div>
                <div className="form-view-wrapper">
                    <FormView formDefinition={FormStudio.formDef}/>
                </div>

                <div className="form-editor">
                    <Tabs>
                        <Tabs.TabPane tab="控件属性" key='1'>
                            <ComponentPropsEditor/>
                        </Tabs.TabPane>
                        <Tabs.TabPane tab="表单属性" key='2'>
                            <FormPropsEditor definition={FormStudio.formDef}/>
                        </Tabs.TabPane>
                    </Tabs>
                </div>
            </div>
        );
    }
}

export default FormDesigner;

// antdv-designer/src/designer/FormDesigner.vue
<template>
  <div class="form-designer">
    <div class="form-widget">
      <Tabs v-model:activeKey="activeKey">
        <tab-pane tab="表单组件" key='1'>
          <div class="widgetList">
            <form-widget v-for="comp in compList" :key="comp.type" :type="comp.type" :title="comp.title"/>
          </div>
        </tab-pane>
        <tab-pane tab="布局" key='2'>
          <div class="widgetList">
            <form-widget v-for="comp in layoutList" :key="comp.type" :type="comp.type" :title="comp.title"/>
          </div>
        </tab-pane>
      </Tabs>
    </div>
    <div class="form-view-wrapper">
      <form-view :formDefinition="fromDef" :definition="definition"></form-view>
    </div>
    <div class="form-editor">
      <Tabs v-model:activeKey="activeKeyRight">
        <tab-pane tab="控件属性" key='1'>
          <ComponentPropsEditor/>
        </tab-pane>
        <tab-pane tab="表单属性" key='2'>
          <FormPropsEditor/>
        </tab-pane>
      </Tabs>
    </div>
  </div>
</template>

<script lang="ts">
import {Tabs} from 'ant-design-vue';
import {computed, defineComponent, ref} from "vue";
import FormView from './FormView.vue'
import FormStudio from "@@/FormStudio";
import {FactoryGroup} from "@@/types";
import FormWidget from "@/designer/FormWidget.vue";
import ComponentPropsEditor from "@/designer/ComponentPropsEditor.vue";
import FormPropsEditor from "@/designer/FormPropsEditor.vue";

export default defineComponent({
  name: "FormDesigner",
  components: {
    FormPropsEditor,
    ComponentPropsEditor,
    FormWidget,
    Tabs,
    FormView,
    TabPane: Tabs.TabPane
  },
  setup() {
    const componentList = FormStudio.factoryFilter((it) => true);

    const layoutList = computed(() => {
      return componentList.filter(it => it.group == FactoryGroup.Layout)
    })

    const compList = computed(() => {
      return componentList.filter(it => it.group == FactoryGroup.Component)
    })

    return {
      layoutList,
      compList,
      fromDef: FormStudio.formDef,
      definition: FormStudio.definition,
      activeKey: ref('1'),
      activeKeyRight: ref('1')
    }
  }
})
</script>

<style lang="less">
@import "@@/style/formView.less";
@import "@@/style/component.less";
</style>
